/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { FakeFxRoot, FakeFxRootInterface } from "../FakeFxRoot";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_receiver",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "_data",
        type: "bytes",
      },
    ],
    name: "sendMessageToChild",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_fxChild",
        type: "address",
      },
    ],
    name: "setFxChild",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506102cd806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063b47204771461003b578063b86cfdcf14610057575b600080fd5b610055600480360381019061005091906101f6565b610073565b005b610071600480360381019061006c91906101cd565b6100a4565b005b61009f7f834a7ccf1c08b22b77ef42f230dfd2e76a1688bf9a5a33276a848c5c69e05cb260001b61016b565b505050565b6100d07fe21003efd288594deec4159d02724dfb58a318046fa78c2651f4b9f1f66f423f60001b61016b565b6100fc7fc732b2562bb765a2142c8f84697e69c0c4be4cefd08ddceae39a42bbec672f9b60001b61016b565b6101287fddc937d2ff1f2979e07976f500998cdfa076b814d3d4d9f58539f98f095daaf360001b61016b565b806000806101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b50565b60008135905061017d81610280565b92915050565b60008083601f84011261019557600080fd5b8235905067ffffffffffffffff8111156101ae57600080fd5b6020830191508360018202830111156101c657600080fd5b9250929050565b6000602082840312156101df57600080fd5b60006101ed8482850161016e565b91505092915050565b60008060006040848603121561020b57600080fd5b60006102198682870161016e565b935050602084013567ffffffffffffffff81111561023657600080fd5b61024286828701610183565b92509250509250925092565b600061025982610260565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6102898161024e565b811461029457600080fd5b5056fea2646970667358221220986591f2a87854d60fbebf3c34a2ec9ea022e2570ddaa809442359de1659a00d64736f6c63430008040033";

export class FakeFxRoot__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<FakeFxRoot> {
    return super.deploy(overrides || {}) as Promise<FakeFxRoot>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): FakeFxRoot {
    return super.attach(address) as FakeFxRoot;
  }
  connect(signer: Signer): FakeFxRoot__factory {
    return super.connect(signer) as FakeFxRoot__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): FakeFxRootInterface {
    return new utils.Interface(_abi) as FakeFxRootInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): FakeFxRoot {
    return new Contract(address, _abi, signerOrProvider) as FakeFxRoot;
  }
}
