/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICloneAbleERC721,
  ICloneAbleERC721Interface,
} from "../ICloneAbleERC721";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "name_",
        type: "string",
      },
      {
        internalType: "string",
        name: "symbol_",
        type: "string",
      },
      {
        internalType: "address",
        name: "_L2Tunnel",
        type: "address",
      },
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "initialize",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class ICloneAbleERC721__factory {
  static readonly abi = _abi;
  static createInterface(): ICloneAbleERC721Interface {
    return new utils.Interface(_abi) as ICloneAbleERC721Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICloneAbleERC721 {
    return new Contract(address, _abi, signerOrProvider) as ICloneAbleERC721;
  }
}
