/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IFakeFxChild, IFakeFxChildInterface } from "../IFakeFxChild";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "stateId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "receiver",
        type: "address",
      },
      {
        internalType: "address",
        name: "rootMessageSender",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "data",
        type: "bytes",
      },
    ],
    name: "onStateReceive",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IFakeFxChild__factory {
  static readonly abi = _abi;
  static createInterface(): IFakeFxChildInterface {
    return new utils.Interface(_abi) as IFakeFxChildInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IFakeFxChild {
    return new Contract(address, _abi, signerOrProvider) as IFakeFxChild;
  }
}
